export type HiringMessageKind = 'vacancy' | 'candidate' | 'vacancy_digest' | 'recruitment_ad' | 'course' | 'job_service' | 'closed_vacancy' | 'spam' | 'unknown';
export type ContextualLanguage = Readonly<{
  language: string;
  name: string;
  relation: 'required' | 'preferred' | 'notRequired' | 'candidateHas' | null;
  level: string | null;
  cefr: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2' | null;
  start: number;
  end: number;
}>;
export type HiringContextResult = Readonly<{
  kind: HiringMessageKind | string;
  sections: Readonly<Record<string, string>>;
  profession: Readonly<Record<string, unknown>>;
  languages: readonly ContextualLanguage[];
  requirementRelations: readonly string[];
  hasResponsibilities: boolean;
  hasOfferSection: boolean;
  contacts: readonly string[];
  application: readonly string[];
  companyContext: readonly string[];
  locationContext: readonly string[];
  workAuthorization: readonly string[];
  availability: readonly string[];
  travel: string | null;
  relocation: string | null;
  bonuses: readonly string[];
  benefits: readonly string[];
  contracts: readonly string[];
  openingCount: number | null;
  vacancyStatus: string | null;
  candidateStatus: string | null;
  candidatePreferences: readonly string[];
  employmentHistoryContext: readonly string[];
  educationContext: string | null;
  driverContext: readonly string[];
  noticePeriod: Readonly<{ value: number; unit: 'day' | 'week' }> | null;
}>;
export const REQUIREMENT_TERMS: readonly unknown[];
export const RESPONSIBILITY_TERMS: readonly unknown[];
export const OFFER_TERMS: readonly unknown[];
export const CONTACT_TERMS: readonly unknown[];
export const APPLICATION_TERMS: readonly unknown[];
export const COMPANY_TERMS: readonly unknown[];
export const LOCATION_CONTEXT_TERMS: readonly unknown[];
export const WORK_AUTHORIZATION_TERMS: readonly unknown[];
export const HIRING_AVAILABILITY_TERMS: readonly unknown[];
export const TRAVEL_TERMS: readonly unknown[];
export const RELOCATION_CONTEXT_TERMS: readonly unknown[];
export const BONUS_TERMS: readonly unknown[];
export const CONTRACT_CONTEXT_TERMS: readonly unknown[];
export const VACANCY_STATUS_TERMS: readonly unknown[];
export const CANDIDATE_STATUS_TERMS: readonly unknown[];
export const CANDIDATE_PREFERENCE_TERMS: readonly unknown[];
export const EMPLOYMENT_HISTORY_TERMS: readonly unknown[];
export const EDUCATION_CONTEXT_TERMS: readonly unknown[];
export const DRIVER_CONTEXT_TERMS: readonly unknown[];
export const HIRING_SECTION_MARKERS: Readonly<Record<string, unknown>>;
export const HIRING_NON_CONTENT_TERMS: readonly unknown[];
export function splitHiringSections(value: unknown): Readonly<Record<string, string>>;
export function parseLanguageContext(value: unknown, options?: { mode?: 'vacancy' | 'candidate' | null }): readonly ContextualLanguage[];
export function resolveProfessionContext(value: unknown, options?: { mode?: 'vacancy' | 'candidate' | null; title?: string }): Readonly<Record<string, unknown>>;
export function classifyHiringMessage(value: unknown): HiringMessageKind;
export function parseHiringContext(value: unknown, options?: { mode?: 'vacancy' | 'candidate' | null; title?: string }): HiringContextResult;
