export type HousingPolicy = 'allowed' | 'notAllowed' | 'conditional' | null;
export type HousingContextResult = Readonly<{
  condition: string | null;
  layouts: readonly string[];
  buildingType: string | null;
  buildingStatus: string | null;
  priceContext: string | null;
  priceModifiers: readonly string[];
  rentDuration: string | null;
  floorConstraints: readonly string[];
  furniture: string | null;
  tenantPolicies: Readonly<{ pets: HousingPolicy; children: HousingPolicy; smoking: HousingPolicy }>;
  documents: readonly string[];
  financing: readonly string[];
  locationRelations: readonly string[];
  availability: string | null;
  listingStatus: string | null;
}>;
export const PROPERTY_CONDITION_TERMS: readonly unknown[];
export const LAYOUT_TERMS: readonly unknown[];
export const BUILDING_TYPE_TERMS: readonly unknown[];
export const BUILDING_STATUS_TERMS: readonly unknown[];
export const PROPERTY_PRICE_CONTEXT: readonly unknown[];
export const PRICE_MODIFIERS: readonly unknown[];
export const RENT_DURATION_TERMS: readonly unknown[];
export const FLOOR_CONSTRAINT_TERMS: readonly unknown[];
export const FURNITURE_STATE_TERMS: readonly unknown[];
export const PET_POLICY_TERMS: readonly unknown[];
export const CHILD_POLICY_TERMS: readonly unknown[];
export const SMOKING_POLICY_TERMS: readonly unknown[];
export const DOCUMENT_STATUS_TERMS: readonly unknown[];
export const FINANCING_TERMS: readonly unknown[];
export const LOCATION_RELATIONS: readonly unknown[];
export const AVAILABILITY_TERMS: readonly unknown[];
export const LISTING_STATUS_TERMS: readonly unknown[];
export function parseHousingContext(value: unknown): HousingContextResult;
