export type HousingAudience = 'women' | 'men' | 'family';
export interface HousingPerPersonPrice { amount: number; currency: string | null; approximate: boolean; scope: 'person' }
export interface HousingCommissionAmount { amount: number; currency: string | null; approximate: boolean }
export interface HousingListingEnrichment {
  rooms?: number | null;
  areaSqm?: number | null;
  floor?: number | null;
  totalFloors?: number | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  balcony?: boolean | null;
  terrace?: boolean | null;
  privateYard?: boolean | null;
  dishwasher?: boolean | null;
  airConditioner?: boolean | null;
  gas?: boolean | null;
  newBuilding?: boolean | null;
  communalSeparated?: boolean | null;
  parking?: boolean | null;
  elevator?: boolean | null;
  heating?: boolean | null;
  hotWater?: boolean | null;
  internet?: boolean | null;
  petsAllowed?: boolean | null;
  childrenAllowed?: boolean | null;
  smokingAllowed?: boolean | null;
  negotiable?: boolean | null;
  furnished?: boolean | null;
  deposit?: boolean | null;
  firstRental?: boolean | null;
  utilitiesAmount?: { amount: number; currency: string | null; approximate?: boolean } | null;
  commission?: boolean | null;
  commissionPercent?: number | null;
  commissionAmount?: HousingCommissionAmount | null;
  audience?: HousingAudience | null;
  audienceAlternatives?: readonly HousingAudience[];
  roomOnly?: boolean;
  studentTarget?: boolean;
  landlordPresent?: boolean;
  priceScope?: 'person' | null;
  perPersonPrice?: HousingPerPersonPrice | null;
  transitRoutes?: readonly string[];
  walkMinutes?: number | null;
  nearby?: readonly string[];
  amenities?: readonly string[];
  district?: string | null;
  quarter?: { number: number; suffix: string } | null;
  metro?: string | null;
  residenceComplex?: string | null;
  address?: string | null;
  addressStreet?: string | null;
  addressHouseNumber?: string | null;
  addressBuilding?: string | null;
}

export function parseHousingNearby(value: unknown): readonly string[];
export function parseHousingAudience(value: unknown): Readonly<{ primary: HousingAudience | null; alternatives: readonly HousingAudience[] }>;
export function parseHousingRoomShare(value: unknown): boolean;
export function parseHousingLandlordPresent(value: unknown): boolean;
export function parseHousingStudentTarget(value: unknown): boolean;
export function parseHousingCommission(value: unknown): boolean | null;
export function parseHousingCommissionAmount(value: unknown): HousingCommissionAmount | null;
export function parseHousingPerPersonPrice(value: unknown, options?: { country?: string }): HousingPerPersonPrice | null;
export function parseHousingTransitRoutes(value: unknown): readonly string[];
export function parseHousingObservedAmenities(value: unknown): readonly string[];
export function parseHousingListingEnrichment(value: unknown, options?: { country?: string }): Readonly<HousingListingEnrichment>;
